// NPM
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { useTranslation } from 'next-i18next'
// Local
import { prisma } from 'lib/prisma'
// Components
import Head from 'next/head'
import Layout from '@/components/Layout'
import LoadingIndicator from '@/components/LoadingIndicator'
import CardsContainer from '@/components/CardsContainer'
import Message from '@/components/Message'
// Styles
import styles from '@/styles/Home.module.css'
import utils from '@/styles/utils.module.css'

export async function getStaticProps({ locale }) {
  const blogs = await prisma.blog.findMany()
  const posts = await prisma.post.findMany()
  return {
    props: {
      ...(await serverSideTranslations(locale, ['index', 'common'])),
      blogs: JSON.parse(JSON.stringify(blogs)),
      posts: JSON.parse(JSON.stringify(posts)),
    },
  }
}

export default function Home({ blogs, posts }) {
  const { t } = useTranslation(['index', 'common'])

  return (
    <>
      <Head>
        <title>{t('head.title', { ns: 'index' })}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={`${styles.main} ${utils.container}`}>
          <h1 className={utils.bigTitle}>{t('body.title', { ns: 'index' })}</h1>
          <div className={styles.blogsContainer}>
            <h2 className={utils.mediumTitle}>Blogs</h2>
            {!blogs ? (
              <LoadingIndicator />
            ) : blogs.length > 0 ? (
              <CardsContainer
                cardsName="blogs"
                cards={blogs}
                linkText={t('cardsContainerText', { ns: 'common' })}
              />
            ) : (
              <Message type="info" message="Aún no hay blogs publicados" />
            )}
          </div>
          <div className={styles.postsContainer}>
            <h2 className={utils.mediumTitle}>Atracciones Judaicas</h2>
            {!posts ? (
              <LoadingIndicator />
            ) : posts.length > 0 ? (
              <CardsContainer
                cardsName="posts"
                cards={posts}
                linkText={t('cardsContainerText', { ns: 'common' })}
              />
            ) : (
              <Message type="info" message="Aún no hay posts publicados" />
            )}
          </div>
        </main>
      </Layout>
    </>
  )
}
