// NPM
import { useEffect, useState } from 'react'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { useTranslation } from 'next-i18next'
// Local
import { fetchStrapi } from 'lib/api'
import { handleError } from 'lib/errors'
// Components
import Head from 'next/head'
import Layout from '@/components/Layout'
import LoadingIndicator from '@/components/LoadingIndicator'
import CardsContainer from '@/components/CardsContainer'
import Message from '@/components/Message'
// Styles
import styles from '@/styles/Home.module.css'
import utils from '@/styles/utils.module.css'

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
    },
  }
}

export default function Home() {
  const [blogs, setBlogs] = useState([])
  const [posts, setPosts] = useState([])
  const [isBlogsLoading, setIsBlogsLoading] = useState(false)
  const [isPostsLoading, setIsPostsLoading] = useState(false)
  const [error, setError] = useState({})

  const { t } = useTranslation('common')

  useEffect(() => {
    async function fetchBlogs() {
      setIsBlogsLoading(true)
      try {
        const { data: blogsData, error } = await fetchStrapi(
          'blogs',
          '?pagination[page]=1&pagination[pageSize]=10'
        )
        if (error) handleError(error)
        setBlogs(blogsData)
      } catch (error) {
        setError((prevValue) => ({ ...prevValue, blogs: error.message }))
      }
      setIsBlogsLoading(false)
    }
    async function fetchPosts() {
      setIsPostsLoading(true)
      try {
        const { data: postsData, error } = await fetchStrapi(
          'posts',
          '?pagination[page]=1&pagination[pageSize]=10'
        )
        if (error) handleError(error)
        setPosts(postsData)
      } catch (error) {
        setError((prevValue) => ({ ...prevValue, posts: error.message }))
      }
      setIsPostsLoading(false)
    }
    fetchBlogs()
    fetchPosts()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={`${styles.main} ${utils.container}`}>
          <h1 className={utils.bigTitle}>Bienvenido a turismojudaico</h1>
          <div className={styles.blogsContainer}>
            <h2 className={utils.mediumTitle}>Blogs</h2>
            {error.blogs ? (
              <Message type="error" message={error.blogs} />
            ) : (blogs.length === 0 && !isBlogsLoading) || isBlogsLoading ? (
              <LoadingIndicator />
            ) : blogs.length > 0 ? (
              <CardsContainer
                cardsName="blogs"
                cards={blogs}
                linkText={t('cardsContainerText')}
              />
            ) : (
              <Message type="info" message="Aún no hay blogs publicados" />
            )}
          </div>
          <div className={styles.postsContainer}>
            <h2 className={utils.mediumTitle}>Atracciones Judaicas</h2>
            {error.posts ? (
              <Message type="error" message={error.posts} />
            ) : (posts.length === 0 && !isPostsLoading) || isPostsLoading ? (
              <LoadingIndicator />
            ) : posts.length > 0 ? (
              <CardsContainer
                cardsName="posts"
                cards={posts}
                linkText={t('cardsContainerText')}
              />
            ) : (
              <Message type="info" message="Aún no hay posts publicados" />
            )}
          </div>
        </main>
      </Layout>
    </>
  )
}
